conformance - remove unused curses dependency
Otherwise couldn't run conformance on Windows at all:
```
Traceback (most recent call last):
  File "L:\Projects\Github\typing\conformance\src\main.py", line 16, in <module>
    from reporting import generate_summary
  File "L:\Projects\Github\typing\conformance\src\reporting.py", line 10, in <module>
    from type_checker import TYPE_CHECKERS
  File "L:\Projects\Github\typing\conformance\src\type_checker.py", line 6, in <module>
    from curses.ascii import isspace
  File "L:\Software\Python312\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```